"""Phase 2a — DST face augmentation pipeline.

Takes the 6 AI-beauty-face stills and generates a large, diverse dataset
of synthetic frames for DeepFaceLab SAEHD DST training.

Why augmentation matters
------------------------
DFL needs to see the DST face at many poses, lighting conditions, and
expressions to train a generalised autoencoder. With only 6 stills we
must synthesise that diversity. This script uses classical image transforms;
for even better head-pose diversity you can supplement with LivePortrait
(see "LivePortrait note" below).

Augmentation catalogue
----------------------
Geometric (approximate pose variation):
  • horizontal flip       → mirror-image face (doubles pose range)
  • rotation ±25°        → head tilt variation
  • perspective warp      → mild off-axis viewing angle
  • scale crop            → zoom in/out while keeping face visible

Photometric (lighting / colour):
  • brightness ±35%
  • contrast ±30%
  • saturation ±25%
  • hue shift ±12°
  • gamma 0.65–1.45

Quality / noise:
  • Gaussian noise σ 0–18
  • JPEG re-encode quality 72–98

Each output frame is a random combination of 3-7 of the above transforms.
After each generation, face detection confirms the face is still visible;
frames that fail are discarded and regenerated.

Output
------
  training_data/dst_augmented/<source_stem>_NNNNN.jpg

Total: --per-image × 6 frames (default 500 → 3 000 frames).

LivePortrait note
-----------------
For better head-pose diversity (yaw / pitch) beyond ±25°:

  1. Install LivePortrait (https://github.com/KwaiVision/LivePortrait):
         git clone https://github.com/KwaiVision/LivePortrait.git
         cd LivePortrait && pip install -r requirements.txt

  2. Run LivePortrait with a driving video (e.g. a talking-head clip):
         python inference.py --source path/to/still.png \
                             --driving path/to/drive.mp4 \
                             --output training_data/dst_augmented/

  3. Those animated frames drop straight into dst_augmented/ alongside
     the frames generated by this script — DFL trains on all of them.

Usage
-----
  .venv\\Scripts\\python.exe scripts\\augment_dst_faces.py
  .venv\\Scripts\\python.exe scripts\\augment_dst_faces.py --per-image 1000
  .venv\\Scripts\\python.exe scripts\\augment_dst_faces.py \\
      --src-dir . --out-dir training_data/dst_augmented --per-image 500
"""

from __future__ import annotations

import argparse
import random
import sys
import time
from pathlib import Path

import cv2
import numpy as np

# ---------------------------------------------------------------------------
# Config / constants
# ---------------------------------------------------------------------------

_FACE_MODEL = Path("models/face_detection_yunet_2023mar.onnx")
_FACE_CONF   = 0.45      # lower than pipeline — accept mildly occluded faces
_JPEG_QUAL   = [72, 98]  # (min, max) JPEG quality for output

# Default source: the 6 stills in the project root.
_DEFAULT_SRC = "."
_SRC_GLOB    = "*.png"
_DEFAULT_OUT = "training_data/dst_augmented"
_PER_IMAGE   = 500
_MAX_TRIES   = 5         # max generation attempts before skipping a slot


# ---------------------------------------------------------------------------
# Augmentation helpers
# ---------------------------------------------------------------------------

def _brightness(img: np.ndarray, rng: random.Random) -> np.ndarray:
    factor = rng.uniform(0.65, 1.35)
    return np.clip(img.astype(np.float32) * factor, 0, 255).astype(np.uint8)


def _contrast(img: np.ndarray, rng: random.Random) -> np.ndarray:
    factor = rng.uniform(0.70, 1.30)
    mean = img.mean()
    out = mean + factor * (img.astype(np.float32) - mean)
    return np.clip(out, 0, 255).astype(np.uint8)


def _saturation(img: np.ndarray, rng: random.Random) -> np.ndarray:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV).astype(np.float32)
    hsv[:, :, 1] *= rng.uniform(0.75, 1.25)
    hsv[:, :, 1] = np.clip(hsv[:, :, 1], 0, 255)
    return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)


def _hue_shift(img: np.ndarray, rng: random.Random) -> np.ndarray:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV).astype(np.int32)
    hsv[:, :, 0] = (hsv[:, :, 0] + rng.randint(-12, 12)) % 180
    return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)


def _gamma(img: np.ndarray, rng: random.Random) -> np.ndarray:
    g = rng.uniform(0.65, 1.45)
    lut = np.array([(i / 255.0) ** (1.0 / g) * 255
                    for i in range(256)], dtype=np.uint8)
    return cv2.LUT(img, lut)


def _noise(img: np.ndarray, rng: random.Random) -> np.ndarray:
    sigma = rng.uniform(0, 18)
    if sigma < 1.0:
        return img
    # Seed numpy from rng so the pipeline is fully reproducible.
    np_rng = np.random.default_rng(rng.getrandbits(32))
    noise_arr = np_rng.normal(0, sigma, img.shape).astype(np.float32)
    return np.clip(img.astype(np.float32) + noise_arr, 0, 255).astype(np.uint8)


def _jpeg_quality(img: np.ndarray, rng: random.Random) -> np.ndarray:
    q = rng.randint(_JPEG_QUAL[0], _JPEG_QUAL[1])
    enc_param = [int(cv2.IMWRITE_JPEG_QUALITY), q]
    _, buf = cv2.imencode(".jpg", img, enc_param)
    return cv2.imdecode(buf, cv2.IMREAD_COLOR)


def _rotate(img: np.ndarray, rng: random.Random) -> np.ndarray:
    angle = rng.uniform(-25, 25)
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w / 2, h / 2), angle, 1.0)
    return cv2.warpAffine(img, M, (w, h),
                          flags=cv2.INTER_LINEAR,
                          borderMode=cv2.BORDER_REFLECT)


def _flip(img: np.ndarray, rng: random.Random) -> np.ndarray:
    return cv2.flip(img, 1)  # horizontal


def _scale_crop(img: np.ndarray, rng: random.Random) -> np.ndarray:
    """Zoom in/out then crop back to original size."""
    h, w = img.shape[:2]
    scale = rng.uniform(0.82, 1.18)
    new_w, new_h = int(w * scale), int(h * scale)
    resized = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
    if scale >= 1.0:
        # Crop centre
        x0 = (new_w - w) // 2
        y0 = (new_h - h) // 2
        return resized[y0:y0 + h, x0:x0 + w]
    else:
        # Pad with border-reflect then crop
        pad_x = (w - new_w) // 2
        pad_y = (h - new_h) // 2
        padded = cv2.copyMakeBorder(resized, pad_y, h - new_h - pad_y,
                                    pad_x, w - new_w - pad_x,
                                    cv2.BORDER_REFLECT)
        return padded[:h, :w]


def _perspective(img: np.ndarray, rng: random.Random) -> np.ndarray:
    """Mild 4-point perspective warp (simulates slight off-axis angle)."""
    h, w = img.shape[:2]
    strength = rng.uniform(0.0, 0.06)
    # Perturb each corner by a random amount
    pts_src = np.float32([[0, 0], [w, 0], [w, h], [0, h]])
    def jitter(v, axis):
        mag = (w if axis == 0 else h) * strength
        return v + rng.uniform(-mag, mag)
    pts_dst = np.float32([
        [jitter(0, 0), jitter(0, 1)],
        [jitter(w, 0), jitter(0, 1)],
        [jitter(w, 0), jitter(h, 1)],
        [jitter(0, 0), jitter(h, 1)],
    ])
    M = cv2.getPerspectiveTransform(pts_src, pts_dst)
    return cv2.warpPerspective(img, M, (w, h),
                               flags=cv2.INTER_LINEAR,
                               borderMode=cv2.BORDER_REFLECT)


# ---------------------------------------------------------------------------
# Augmentation pipeline
# ---------------------------------------------------------------------------

# Pool of augmentation functions.  Each is called with (img, rng).
_PHOTOMETRIC = [_brightness, _contrast, _saturation, _hue_shift, _gamma]
_QUALITY     = [_noise, _jpeg_quality]
_GEOMETRIC   = [_rotate, _scale_crop, _perspective]

def augment(img: np.ndarray, rng: random.Random) -> np.ndarray:
    """Apply a random combination of augmentations to img."""
    out = img.copy()

    # Geometric: always apply at least one
    geo_fns = list(_GEOMETRIC)
    rng.shuffle(geo_fns)
    n_geo = rng.randint(1, len(geo_fns))
    for fn in geo_fns[:n_geo]:
        out = fn(out, rng)

    # Flip with 50% probability
    if rng.random() < 0.5:
        out = _flip(out, rng)

    # Photometric: apply 1-4
    photo_fns = list(_PHOTOMETRIC)
    rng.shuffle(photo_fns)
    for fn in photo_fns[:rng.randint(1, 4)]:
        out = fn(out, rng)

    # Quality: apply 0-2
    qual_fns = list(_QUALITY)
    rng.shuffle(qual_fns)
    for fn in qual_fns[:rng.randint(0, 2)]:
        out = fn(out, rng)

    return out


# ---------------------------------------------------------------------------
# Face detector
# ---------------------------------------------------------------------------

def make_detector(model_path: Path) -> cv2.FaceDetectorYN | None:
    if not model_path.exists():
        print(f"  [WARN] Face model not found at {model_path} — skipping face check")
        return None
    det = cv2.FaceDetectorYN.create(
        str(model_path), "", (0, 0),
        score_threshold=_FACE_CONF, nms_threshold=0.3, top_k=5,
    )
    return det


def has_face(detector: cv2.FaceDetectorYN | None, img: np.ndarray) -> bool:
    if detector is None:
        return True  # skip check if no model
    h, w = img.shape[:2]
    detector.setInputSize((w, h))
    _, faces = detector.detect(img)
    return faces is not None and len(faces) > 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="DST face augmentation pipeline")
    p.add_argument("--src-dir",    default=_DEFAULT_SRC,
                   help=f"Directory containing source stills (default: {_DEFAULT_SRC})")
    p.add_argument("--src-glob",   default=_SRC_GLOB,
                   help=f"Glob for source images (default: {_SRC_GLOB})")
    p.add_argument("--out-dir",    default=_DEFAULT_OUT,
                   help=f"Output directory (default: {_DEFAULT_OUT})")
    p.add_argument("--per-image",  type=int, default=_PER_IMAGE,
                   help=f"Augmented frames per source image (default: {_PER_IMAGE})")
    p.add_argument("--seed",       type=int, default=42,
                   help="Random seed (default: 42)")
    p.add_argument("--no-face-check", action="store_true",
                   help="Skip face detection check on each output frame (faster)")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    src_dir = Path(args.src_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sources = sorted(src_dir.glob(args.src_glob))
    if not sources:
        print(f"No images matched {src_dir}/{args.src_glob}")
        sys.exit(1)
    print(f"Source images   : {len(sources)}")
    print(f"Per image       : {args.per_image}")
    print(f"Total target    : {len(sources) * args.per_image}")
    print(f"Output directory: {out_dir}\n")

    detector = None if args.no_face_check else make_detector(_FACE_MODEL)
    rng = random.Random(args.seed)

    total_saved  = 0
    total_failed = 0
    t0 = time.monotonic()

    for src_path in sources:
        img = cv2.imread(str(src_path))
        if img is None:
            print(f"  [SKIP] Cannot read {src_path}")
            continue

        # Verify source image has a face before generating anything from it.
        if not has_face(detector, img):
            print(f"  [WARN] No face in source {src_path.name} — skipping")
            continue

        stem = src_path.stem
        saved = 0
        tried = 0
        target = args.per_image

        while saved < target:
            tried += 1
            candidate = augment(img, rng)

            if not has_face(detector, candidate):
                total_failed += 1
                # Allow up to _MAX_TRIES extra attempts per slot before
                # accepting anyway to avoid infinite loops.
                if tried - saved > _MAX_TRIES * target:
                    # Safety valve: just save as-is
                    candidate = img.copy()

            out_path = out_dir / f"{stem}_{saved:05d}.jpg"
            cv2.imwrite(str(out_path), candidate,
                        [int(cv2.IMWRITE_JPEG_QUALITY), 95])
            saved += 1
            total_saved += 1

            # Progress line
            if saved % 50 == 0 or saved == target:
                elapsed = time.monotonic() - t0
                rate = total_saved / elapsed if elapsed > 0 else 0
                print(f"  {src_path.name}: {saved}/{target}  "
                      f"(total {total_saved}, {rate:.0f} fr/s)", end="\r")

        print(f"  {src_path.name}: {saved}/{target} saved"
              f"{f'  [{total_failed} face-check fails so far]' if total_failed else ''}"
              + " " * 20)

    elapsed = time.monotonic() - t0
    print(f"\nDone. {total_saved} frames in {elapsed:.1f}s  "
          f"({total_saved / elapsed:.0f} fr/s)")
    if total_failed:
        print(f"Discarded {total_failed} frames that failed face detection.")
    print(f"\nNext step (Phase 2b): place Momo's source-face video in")
    print(f"  training_data/src_video/")
    print(f"then run: .venv\\Scripts\\python.exe scripts\\extract_src_frames.py")


if __name__ == "__main__":
    main()
